@startuml diagram
left to right direction

rectangle "Zarządzanie wersjonowaniem i archiwizacją" {
    actor Administrator
    usecase (Tworzenie kopii zapasowych) as Kopie

    Administrator -- Kopie
}

@enduml