@startuml


|s| System

start
:Zarzadzanie zbiorami danych;
if (Zbiór nadal istnieje?) then (Tak)
  if (Zbiór jest duplikatem?) then (Nie)
    if (Zbiór zawiera błędy?) then (Nie)
      if (Zbiór wymaga modyfikacji?) then (Tak)
        :Dokonaj modyfikacji zbioru;
      else (Nie)
      endif
      stop
    else(Tak)
    endif
  else (Tak)
  endif
else (Nie)
endif
:Usuń zbiór;
stop
@enduml