@startuml
|#palegreen|u|Użytkownik
|System|

|u|
start
:Wybór zakresu raportu;

|System|
:System pobiera dane;

:System analizuje dane;

:System generuje raport;

:System udostępnia raport;

|u|
:Odbiór raportu;

stop
@enduml
