@startuml
|u| Użytkownik
start
:Wysyła zgłoszenie;

|s| System
:Zapisuje zgłoszenie;

|a| Administrator
:Weryfikuje zgłoszenie;

if (Błąd potwierdzony?) then (Tak)
  :Zatwierdza poprawkę;
  |s| System
  :Aktualizuje dane;
  |a| Administrator
  :Wysyła decyzję do użytkownika (błąd poprawiony);
else (Nie)
  :Odrzuca zgłoszenie;
  :Wysyła decyzję do użytkownika (błąd niepoprawiony);
endif

|u| Użytkownik
:Otrzymuje komunikat o decyzji;
stop
@enduml
