@startuml

|#gold|a| Administrator
|s| System
|a|

start
if (Czy zbiór wymaga działania?) then (Tak)
  if (Czy zbiór należy usunąć?) then (Nie)
    if (Czy zbiór należy zmodyfikować?) then (Nie)
    else (Tak)
    :Wydaj polecenie modyfikacji zbioru;
    |s|
    :Wykonaj modyfikację zbioru;
    endif
    
  else (Tak)
  |a|
  :Wydaj polecenie archiwizacji zbioru i ukrycia;
  |s|
  :Wykonaj archiwizację zbioru i ukryj;
  endif
else (Nie)
endif
stop

@enduml