@startuml
 
start
:Zbieranie danych ;
:Oczyszczanie i standaryzacja danych;
:Analiza oraz agregacja danych;
:Wyodrębnianie kluczowych wskaźników;
:Tworzenie wizualizacji (raporty, wykresy, dashboardy);
:Dystrybucja zestawów danych;
stop
@enduml