@startuml
|u| Użytkownik
start
:Wprowadza dane logowania;

|s| System
if (Czy konto istnieje?) then (Tak)
  :Sprawdzenie poprawności hasła;
  if (Czy hasło jest poprawne?) then (Tak)
    :Sprawdzenie poziomu dostępu;
    :Przyznanie dostępu do systemu;
    stop
  else (Nie)
    :Odrzucenie dostępu (niepoprawne hasło);
    |u| Użytkownik
    :Wyświetlenie komunikatu;
    stop
  endif
else (Nie)
  :Odrzucenie dostępu (konto nie istnieje);
  |u| Użytkownik
  :Wyświetlenie komunikatu;
  stop
endif
@enduml
