@startuml
|a| Administrator
start
:Przesyła dane źródła przez API;

|s| System
:Waliduje poprawność danych;

if (Czy dane są poprawne?) then (Tak)
  :Rejestracja nowego źródła;
  :Dodanie źródła do bazy danych;
stop
else (Nie)
  :Odrzucenie zgłoszenia;
  |a| Administrator
  :Informowanie o błędach;
stop
endif
@enduml
