name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build pdf
        run: |-
          npm install -g md-to-pdf  
          md-to-pdf README.md
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./README.pdf